# url - куда будет происходить регистрация микросервисов
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# включение определения, перенаправления
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# не обращать внимание на регистр
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# можно вручную перенаправлять запрос на нужный микросервис
# id самого роута
spring.cloud.gateway.server.webflux.routes[0].id=test
# к какому именно инстенсу будет идти обращение (по id)
spring.cloud.gateway.server.webflux.routes[0].uri=lb://eureka-client
# Для методов TestController проксируем все пути /main/**
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/main/**
# а метод будет get (это можно увидеть в классе TestController)
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=GET

# для eclient2
spring.cloud.gateway.server.webflux.routes[1].id=hello
spring.cloud.gateway.server.webflux.routes[1].uri=lb://eureka-client2
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/new/hello
spring.cloud.gateway.server.webflux.routes[1].predicates[1]=Method=GET

# включаем actuator
management.endpoint.gateway.access=read-only
# какие endpoints хотим включить
management.endpoints.web.exposure.include=gateway
