server.port=8082

# настройка соединения с БД
spring.datasource.url=jdbc:postgresql://localhost:5432/planner_todo
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Так приложение быстрее показывает неправильные места, где данные не загружены явно.
spring.jpa.open-in-view=false

# настройка каналов для AMPQ:
# 1. описание названия метода (или группы методов, котрые указываюися через ";") для передачи сообщение по каналам
spring.cloud.function.definition=newActionUserConsume
# 2.
# out - метод newActionUserConsume работает на выход (Planner-users -> MessageFunc -> newActionUserProduce -> Supplier(отправитель))
# 0 - это 1-й тип параметра, который мы отправляем в методе в контейнере Flux - <Message<Long>>
# destination - название канала
spring.cloud.stream.bindings.newActionUserConsume-in-0.destination=planner-dest
spring.cloud.stream.bindings.newActionUserConsume-in-0.group=planner-group
