server.port=8081

# настройка соединения с БД
spring.datasource.url=jdbc:postgresql://localhost:5433/planner_users
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Так приложение быстрее показывает неправильные места, где данные не загружены явно.
spring.jpa.open-in-view=false

tmpVar=555
