# настройка цветов длят лога
spring.output.ansi.enabled=ALWAYS

# формат вывода логов
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr([%-5level]) %clr(%logger{36}){cyan} - %msg%n

# включаем actuator
#management.endpoint.gateway.access=read-only
# какие endpoints хотим включить
#management.endpoints.web.exposure.include=*

management.endpoints.web.exposure.include=health,info,beans,mappings,env,gateway
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.endpoint.gateway.access=read-only
