# настройка цветов длят лога
spring.output.ansi.enabled=DETECT

# формат вывода логов
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr([%-5level]) %clr(%logger{36}){cyan} - %msg%n
